name: Build
on:
    push:
        branches:
            - 'main'
    pull_request:
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: volta-cli/action@v4.0.0
            - name: Install
              run: yarn install --immutable --immutable-cache --check-cache
            - name: Generate docs
              run: yarn run generate:docs
            - name: Build
              run: yarn run build
            - name: Test
              run: yarn run test
            - name: Lint
              run: yarn run lint
