name: Publish to npm
on:
    release:
        types: [created]
jobs:
    npm_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: volta-cli/action@v4.0.1
              with:
                  registry-url: 'https://registry.npmjs.org'
            - name: Install
              run: yarn install --immutable --check-cache
            - name: Build
              run: yarn run build
            - name: Publish
              run: yarn run publish-workspaces
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPMJS_CLOUDFLIGHT_ADMIN_CI_TOKEN }}
